name: Veracode Static Analysis - SCA Agent Scan
on: workflow_dispatch

jobs:
  sca_agent_scan:
    name: SCA Agent Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11.14'
      
      - name: Install pipenv & generate pipenv Pipfile
        shell: bash
        run: |
          python3 -m pip install pipenv && pipenv install -r requirements.txt
      
      - name: Veracode SCA Agent Scan
        id: veracode-sca
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.15
        with:
          debug: true