name: Veracode Static Analysis - Pipeline Scan
on: workflow_dispatch

jobs:
  sca_agent_scan:
    name: SCA Agent Scan
    runs-on: ubuntu-latest
    env:
      SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}

    steps:
      - name: Check out main branch
        uses: actions/checkout@v6

      - name: Install pipenv & generate pipenv Pipfile
        shell: bash
        run: |
          python3 -m venv .venv && .venv/bin/pip install pipenv && .venv/bin/pipenv install -r requirements.txt

      - name: Veracode SCA Agent Scan
        if: always()
        id: pipeline-scan
        run: |
          curl -sSL https://sca-downloads.veracode.com/ci.sh | sh -s scan --json=results.json
      
      - name: Upload results
        uses: actions/upload-artifact@v6
        with:
          name: veracode-artifact
          path: results.json
        